language: clojure
lein: 2.7.1
cache:
  directories:
  - $HOME/.m2
#before_script:
#  - mkdir travis-phantomjs
#  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
#  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
#  - export PATH=$PWD/travis-phantomjs:$PATH
script:
  - lein test
#  - lein doo phantom test-build once
